### PR TITLE
Added the client name to the client list view to make it easier to read the list

### PR DESCRIPTION
**Pull request by stustison**
fixes: #4055 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

**Review by edewit — CHANGES_REQUESTED** [review]
wouldn't it be better to use the name instead of the clientId if it's set instead of introducing a new column? WDYT @xianli123

**Comment by xianli123** [comment]
Hi @edewit, We thought about putting the name out there and even did a rough design. Here is the link: https://marvelapp.com/prototype/6722i0a/screen/70973389

However, after discussion, we gave up that design because the **Name** is not required and the **Name** field is not the client's unique identifier. 

With regard to the original issue https://github.com/keycloak/keycloak-ui/issues/4055, the client ID could also be a human-readable string.  In addition, the client ID is the unique identifier of the client. We may not need to change the Client ID to Name. What do you think?

**Comment by xianli123** [comment]
One thing we wanted to change is the terminology of "Client ID". In the beginning, we wanted to change the "Client ID“ to ”Name" and change the "Name" to the "Display name". But we didn't do that due to the backend limitation.

**Comment by stustison** [comment]
This is most commonly an issue when configuring clients in K8s using the CRDs. You have no control over the client IDs that might be generated by another part of the system. So, yes, they "can" be human readable, but it is up to a different part of the system to generate these IDs and drop in the new resource. If the name was visible, then we could at least attach a real name to each client, which would make it easier to see in the list. Attached what our current client list looks like.
clients

**Comment by xianli123** [comment]
It's weird. I used the local server to run the console, and it looks good. I am not sure why it's different with K8s. Could you please help explain it? @stianst Thanks!

Screen Shot 2022-12-20 at 11 28 13

**Comment by stianst** [comment]
@xianli123 this just depends on how the client is created. A client-id is a machine identifiable id, which can be completely random (like a uuid for instance) or could use a more human friendly name like my-client.

Name on the other hand is aimed purely at humans.

I'd suggest adding both name and client-id to the table, with the name in the first column.

**Comment by xianli123** [comment]
Hi @stianst Thanks! The client ID is a unique identifier for the client, whether it's human-readable or not. In addition, the **Name** is not required. Some users may not set **Name**s for clients. So I think we can add the **Name** to the list but put it after the **Client ID** as shown below.

Screen Shot 2022-12-20 at 17 10 55

If it's possible, we could even allow users to manage the columns as shown in the design here. https://marvelapp.com/prototype/6722i0a/screen/70973389. 

What do you think? Thanks.

**Review by edewit — APPROVED** [review]

**Comment by xianli123** [comment]
Hi @edewit , did you update the client list?

**Pull request merged**
