### PR TITLE
Fix roles attribute test

### PR DESCRIPTION
**Pull request by ssilvert**
## Motivation
Realm roles intermittent test failure.

## Brief Description
In addition to separating clean() and type(), try adding an extra assertion to make sure the page is loaded before we proceed.

## Verification Steps
Just need to run CI many times to see if tests pass. I can't reliably recreate the problem on its own.

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]
LGTM

**Comment by ssilvert** [comment]
CI number 1: All tests passed. Retry.

**Comment by ssilvert** [comment]
CI number 2: All tests passed. Retry.

**Comment by jonkoops** [comment]
Superseded by #4194

**Pull request closed without merging**
