### PR TITLE
Reuse of token in TOTP is possible

### PR DESCRIPTION
**Pull request by mabartos**
DRAFT: Changes can be merged after merging https://github.com/keycloak/keycloak/pull/13867

### CODE REVIEW

**Comment by jonkoops** [comment]
@mabartos You mentioned the same PR in the description, could you link the correct one?

**Review by jonkoops — APPROVED** [review]

**Comment by mabartos** [comment]
@jonkoops Thanks for the review! The PR description contains a link to the PR in `keycloak/keycloak` repo.

**Comment by jonkoops** [comment]
Ah yes, I see now. If you paste the plain link Github will apply some special formatting.

**Comment by mabartos** [comment]
I can confirm, that these changes working with the attached PR.

**Comment by jonkoops** [comment]
Converting this to a draft as it requires an upstream PR to be merged first.

**Comment by mabartos** [comment]
Rebased

**Review by jonkoops — APPROVED** [review]

**Pull request merged**
