### PR TITLE
Short verification_uri for Device Authorization Request

### PR DESCRIPTION
**Pull request by cgeorgilakis**
## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

Related to [Keycloak PR](https://github.com/keycloak/keycloak/pull/16156)

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
I'm marking this as a draft as it requires upstream functionality to be merged first.

**Comment by mposolda** [comment]
@jonkoops @cgeorgilakis FYI. I've created https://github.com/keycloak/keycloak-ui/issues/4214 . I am leaving to you whether to address that issue together with this PR or as a separate / follow-up isse.

But IMO it does not makes much sense to have this new option available in the new admin console when other 2 existing options are missing. It will be good that all 3 options are on the same page (section) as I've mentioned in the #4214

**Comment by jonkoops** [comment]
The upstream PR has been merged so I am marking this as ready to be reviewed.

**Comment by jonkoops** [comment]
@cgeorgilakis could you rebase your PR? Ideally if you could give us [edit rights](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) to your PRs so we can rebase them ourselves.

**Comment by cgeorgilakis** [comment]
I rebase it.

**Comment by jonkoops** [comment]
I am merging this in, the missing fields mentioned in #4214 can be implemented in a separate PR.

**Pull request merged**
