### PR TITLE
Update PatternFly to latest version

### PR DESCRIPTION
**Pull request by thatblindgeye**
## Motivation

Updates to latest PF versions

## Additional Notes

Not something introduced with the latest versions, but in testing the UI I did notice a couple of dropdowns weren't easily navigable via keyboard. The first is the "admin" dropdown in the header (cannot navigate to any of the dropdown items), and the other is the "Master" dropdown in the sidenav (cannot access the "create realm" button).

### CODE REVIEW

**Comment by jonkoops** [comment]
LDAP tests are expected to fail. These test results look good.

**Comment by thatblindgeye** [comment]
@jonkoops Pushed some newer version numbers!

**Comment by jonkoops** [comment]
@thatblindgeye are these the stable versions? Or still pre-release?

**Comment by thatblindgeye** [comment]
@jonkoops confirmed that these are still pre-release

**Comment by thatblindgeye** [comment]
@jonkoops in regards to the latest pre-release version bumps, other than the LDAP failures:

- Rerunning the `user_fed_kerberos_test` locally resulted in the tests passing
- The failures in the `clients_saml_test` I don't believe would have been impacted by anything in the latest versions, as it's failing due to `Expected to find element: .pf-c-modal-box .pf-c-modal-box__title-text, but never found it.`

**Comment by jonkoops** [comment]
@thatblindgeye I've rebased the PR on `main` where we added some commits to fix the tests. It looks like everything is passing now!

**Comment by thatblindgeye** [comment]
@jonkoops The latest release numbers in this PR are now live!

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
Thanks @thatblindgeye!

**Pull request merged**
