### PR TITLE
only load realms when dropdown is opened

### PR DESCRIPTION
**Pull request by edewit**
this will not totally fix the issue but make the console at least usable

fixes: #3381

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

**Comment by ssilvert** [comment]
> How was this handled in the old console? Surely we had to load the realms there as well?

The old console does http://localhost:8180/admin/realms?briefRepresentation=true

But the briefRepresentation only helps the amount of data returned and not the number of records.  The old console also has problems handling a large number of realms.

**Comment by jonkoops** [comment]
In that case, could we not fix this issue better by adding a new API that ensures these responses are paginated? Or perhaps we can return a list with sparse fields (e.g. the `id` and `name`)?

**Comment by ssilvert** [comment]
> In that case, could we not fix this issue better by adding a new API that ensures these responses are paginated? Or perhaps we can return a list with sparse fields (e.g. the `id` and `name`)?

Sparse fields is what `briefRepresentation` does.  @edewit Are we using that already?

But to really fix the problem, we need pagination.

**Comment by edewit** [comment]
Yes we have `briefRepresentation` but it's not enough until we have a better API let's do this workaround so people can still use the console

**Comment by jonkoops** [comment]
I have no problem merging this, but do we have an issue to track a better improvement for this?

**Comment by edewit** [comment]
Don't have a specific issue for it, but it's part of a bigger effort to make keycloak work with multiple tenants and realms

**Comment by jonkoops** [comment]
Then we should have an epic for this perhaps. @ssilvert?

**Comment by ssilvert** [comment]
@edewit Does this fully fix the issue cited?  If not, maybe we should keep the issue open or open a new one.

@jonkoops As for starting an Epic, it's not a bad idea, but I'm not sure how to define the scope of the work.

**Comment by ssilvert** [comment]
@edewit Does this fully fix the issue cited?  If not, maybe we should keep the issue open or open a new one.

@jonkoops As for starting an Epic, it's not a bad idea, but I'm not sure how to define the scope of the work.

**Review by jonkoops — APPROVED** [review]
I am approving this since having this is better than having nothing at all. However we should definitely come up with something better in the future.

**Comment by jonkoops** [comment]
@edewit could you make sure the test failures we are seeing here are not related to your changes? AFAIK we can merge this after.

**Comment by edewit** [comment]
yes, tests are fine!

**Pull request merged**
