### PR TITLE
added missing profileProjection field

### PR DESCRIPTION
**Pull request by edewit**
fixes: #3089

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

**Review by jonkoops — APPROVED** [review]

**Comment by jonkoops** [comment]
We should probably hold this PR until https://github.com/keycloak/keycloak/pull/13429 is merged. Also, if we want to do a patch with all of the functionality of the Admin UI it might not be a good idea to merge things that depend on upstream changes.

Maybe we just want to hop on the next major?

cc @ssilvert

**Comment by ssilvert** [comment]
> We should probably hold this PR until [keycloak/keycloak#13429](https://github.com/keycloak/keycloak/pull/13429) is merged. Also, if we want to do a patch with all of the functionality of the Admin UI it might not be a good idea to merge things that depend on upstream changes.
> 
> Maybe we just want to hop on the next major?
> 
> cc @ssilvert

Looks to me like we definitely have to wait.  It depends on a back end change.

**Comment by ssilvert** [comment]
@edewit @jonkoops Actually, I'm thinking now that we should back out the commit that makes this depend on https://github.com/keycloak/keycloak/pull/13429.  

We need the rest of this fixed ASAP.

**Comment by ssilvert** [comment]
https://github.com/keycloak/keycloak/pull/13429 was just merged.

@edewit @jonkoops If you guys think this is ready, let's merge it.

**Comment by jonkoops** [comment]
LGTM. I am going to merge this in.

**Pull request merged**
