### PR TITLE
Show policy type in form title

### LINKED ISSUE #2041: [UX Review] Fine-tuning of the policy creation page in client Authorization
### Describe the bug

In the **Client > Client details > Authorization > Policy > policy creation** page, the title should be "Create [policy type] policy" on the creation page. It happens to all the policy types.

Screen Shot 2022-02-10 at 2 08 26 PM

### Version

New admin UI

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #2041

### CODE REVIEW

**Comment by jonkoops** [comment]
@ssilvert where can I find the form you mentioned here: https://github.com/keycloak/keycloak-ui/issues/2041#issuecomment-1231611220?

**Review by edewit — APPROVED** [review]

**Comment by ssilvert** [comment]
> @ssilvert where can I find the form you mentioned here: [#2041 (comment)](https://github.com/keycloak/keycloak-ui/issues/2041#issuecomment-1231611220)?

@jonkoops I don't remember.  I typed that in during the meeting in response to something pointed out by someone else.  I guess to find out you will have to view the meeting video.

**Comment by edewit** [comment]
@jonkoops Policies and Profiles are both in the same tab (under realm settings -> client policies) and share ( e.g. copied ) a lot of the code

**Comment by jonkoops** [comment]
I can't find the aforementioned issue in the UI so I will merge this as it resolves the original issue.

**Pull request merged**
