### PR TITLE
Replaced Tabs to RoutableTabs implementation in realm-settings - #3981

### LINKED ISSUE #3981: [UX Review] Left-align the subtab row and main tab row
### Description

In the latest UI, the subtab row and main tab row are left-aligned on some pages, but not the others. We can left-align the subtab row and main tab row to make the UI consistent.

Screen Shot 2022-12-09 at 15 56 02

Screen Shot 2022-12-09 at 15 50 17

### Discussion

_No response_

### Motivation

_No response_

### Details

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
## Motivation
Closes #3981

All subtabs in realm settings are now implemented in the same way and are using RoutableTabs instead of Tabs component. 

## Verification Steps
1. Go to `Realm setttings` and navigate through tabs and subtabs.
2. Verify that the subtabs have now left padding.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

**Comment by agagancarczyk** [comment]
@edewit I'll need to review and fix some of the tests that are failing in this PR.

**Review by edewit — APPROVED** [review]

**Review by jonkoops — CHANGES_REQUESTED** [review]
Looks like the tests are failing again, can you take a look @agagancarczyk?

**Comment by jonkoops** [comment]
Code changes are looking good to me otherwise :+1:

**Comment by jonkoops** [comment]
@agagancarczyk I've started using a new approach to the routable tabs that is compatible with the new version of React Router v6. You can see it in more detail in this PR:https://github.com/keycloak/keycloak-ui/pull/4114.

Essentially it requires you to put call the `useRoutableTab` hook (instead of the `routableTab` function), and store the props for the individual tabs in a variable before spreading them.

The reason for this is that the only way to construct an href in React Router v6 is to call the [`useHref`](https://reactrouter.com/en/main/hooks/use-href) hook. So it is required to call this in a place where hooks make sense.

**Pull request closed without merging**
