### PR TITLE
Rollback to previous code to save user attrs

### PR DESCRIPTION
**Pull request by thotty**
## Motivation

Fix what commit https://github.com/keycloak/keycloak-ui/commit/bce8270e7f9f5b4044c710b2625d229b55ac1013#diff-6c84945ae214f472358360f0b3b2c7dc71867ee497695ec66649087cf610f499L44 broke.

With the object's assign the way it was, it didn't overwrite with the new attribute list when removing one or more items. Only when replacing an existing key.

## Brief Description

I saw here that it was not correctly saving user attributes, with the last change made for version 21.

## Verification Steps

1. Open User Attributes tab.
2. Add key/value item.
3. Save.
4. Remove the previous item.
5. Save again.
6. Shows up the toast message with success but the item still there

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] Axe check has been run and resulting a11y issues have been resolved
- [ ] Manual keyboard and screen reader checks have been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

- before
  Peek 02-03-2023 16-06
- after
  user-attfs-save-ok

### CODE REVIEW

**Comment by thotty** [comment]
Hi, it's my first PR to this repo.

**Comment by thotty** [comment]
I'm trying to write one test, in Cypress, to cover this situation.

**Review by edewit — APPROVED** [review]

**Comment by jonkoops** [comment]
Is this something that needs to be back-ported to patch release? Any related issue logged that this fixes?

**Comment by edewit** [comment]
the issue that it fixes is that without it it's impossible to delete attributes

**Comment by thotty** [comment]
Thanks guys!

**Pull request merged**
