### PR TITLE
Try to fix intermittent test failure

### PR DESCRIPTION
**Pull request by ssilvert**
## Motivation
Realm roles intermittent test failure.
https://cloud.cypress.io/projects/j4yhox/runs/5015/test-results/c9d269d5-43af-42fc-bf50-36b36f552f27

## Brief Description
I believe the problem is due to this code:
`` cy.findByTestId(`${[this.name](http://this.name/)}[${index}].key`).clear().type(key);``

According to Cypress docs, you can't reliably use an action like `clear()` in the middle of a chain.

See https://docs.cypress.io/guides/core-concepts/retry-ability#Only-queries-are-retried

## Verification Steps
Just need to run CI many times to see if tests pass.  I can't reliably recreate the problem on its own.

### CODE REVIEW

**Comment by ssilvert** [comment]
CI number 1: All tests passed.  Retry.

**Comment by ssilvert** [comment]
CI number 2: All tests passed. Retry.

**Comment by ssilvert** [comment]
CI number 3: Failed.  Back to the drawing board.

**Comment by ssilvert** [comment]
CI number 4: All tests passed.  Retry.

**Review by edewit — APPROVED** [review]

**Comment by edewit** [comment]
@ssilvert do you want to merge this?

**Review by jonkoops — APPROVED** [review]
Looks like this might at least fix this specific error, so let's merge this in.

**Comment by ssilvert** [comment]
@edewit Not yet. Want to try a few more runs.

**Comment by ssilvert** [comment]
CI number 5: All tests passed. Retry.

**Pull request merged**
